name: AMD64 Build
on: [push, pull_request]

env:
  SUITE: coverage
  WITH_CRASH_REPORTS: ON

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@v3
      - name: Get processor arch
        run: echo "PROCESSOR_ARCH=`uname -p`" >> $GITHUB_ENV

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Get Submodule Info
        id: get-submodule-info
        run: git ls-tree -r HEAD:3rdparty > ${{github.workspace}}/submodule_info
        shell: bash

      - name: Cache 3rdparty builds
        uses: actions/cache@v2
        with:
          path: |
            ${{github.workspace}}/build/3rdparty/bin
            ${{github.workspace}}/build/3rdparty/usr
            ${{github.workspace}}/build/3rdparty/lib
            ${{github.workspace}}/build/3rdparty/include
          key: ${{ runner.os }}-Debug-${{ hashFiles('submodule_info') }}

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_CRASH_REPORTS=$WITH_CRASH_REPORTS -DWITH_COVERAGE_REPORTS=OFF

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ctest -C $BUILD_TYPE

      - name: Prepare Release
        run: tar --transform 's/.*\///g' -zcvf ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-osirose.tar.gz ${{github.workspace}}/build/bin/*
      - name: Upload linux build
        uses: actions/upload-artifact@v2
        with:
          name: linux_debug_build
          path: ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-osirose.tar.gz
  release:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Get processor arch
      run: echo "PROCESSOR_ARCH=`uname -p`" >> $GITHUB_ENV

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Get Submodule Info
      id: get-submodule-info
      run: git ls-tree -r HEAD:3rdparty > ${{github.workspace}}/submodule_info
      shell: bash

    - name: Cache 3rdparty builds
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/build/3rdparty/bin
          ${{github.workspace}}/build/3rdparty/usr
          ${{github.workspace}}/build/3rdparty/lib
          ${{github.workspace}}/build/3rdparty/include
        key: ${{ runner.os }}-Release-${{ hashFiles('submodule_info') }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -GNinja -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_CRASH_REPORTS=$WITH_CRASH_REPORTS -DWITH_COVERAGE_REPORTS=OFF

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Prepare Release
      run: tar --transform 's/.*\///g' -zcvf ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-osirose.tar.gz ${{github.workspace}}/build/bin/*
    - name: Upload linux build
      uses: actions/upload-artifact@v2
      with:
        name: linux_release_build
        path: ${{github.workspace}}/${{ runner.os }}-${{ env.PROCESSOR_ARCH }}-osirose.tar.gz